version: '3'
services:

  comonitoring:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/comonitoring
    container_name: comonitoring
    command: [ "go", "run", "cmd/comonitoring/main.go" ]

  prometheus:
    image: prom/prometheus:v2.34.0
    container_name: co_monitoring_prometheus
    ports:
      - "9000:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data2:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:8.4.4
    container_name: co_monitoring_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  prometheus-data2:
  grafana-data:
